# Site settings
title: jarxg.github.io
tag_text: jarxg
description: jarxg personal page and blog

url: https://jarxg.github.io
baseurl: ""

# Build settings
markdown: kramdown
exclude: ["README.md"]

plugins:
  - jekyll-mentions

jekyll-mentions: https://twitter.com
