# Site settings
title: Jorge Rangel
email: jarg1985@gmail.com
description: My blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jarxg
github_username:  jarxg

# Build settings
markdown: kramdown
