# Site settings
title: jarxg.github.io
tag_text: jarxg
description: jarxg website

url: ""
baseurl: ""

# Build settings
markdown: kramdown
exclude: ["README.md"]

plugins:
- jekyll-feed
- jekyll-mentions
- jekyll-admin

jekyll-mentions: https://twitter.com
