# Site settings
title: jarxg.github.io
tag_text: jarxg
description: jarxg personal page

# Build settings
markdown: kramdown
exclude: ["README.md"]
plugins: ['jekyll-twitter-plugin']
sass:
  style: compressed

collections:
- _posts